# Generated by Django 3.2.6 on 2021-08-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_api', '0003_alter_crew_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupimage',
            old_name='feed',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='crew',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='group_api.group'),
        ),
    ]
