# Generated by Django 3.2.6 on 2021-09-17 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_profile_introduction'),
        ('feed_api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hash_prof', to='user_api.profile'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='feed_api.feed'),
        ),
    ]
