# Generated by Django 3.2.5 on 2021-08-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_api', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='post_type',
            field=models.IntegerField(choices=[(0, 'feed'), (1, 'comment')], default=0),
        ),
    ]
