# Generated by Django 3.2.6 on 2021-08-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_api', '0003_cocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_type',
            field=models.IntegerField(null=True),
        ),
    ]
