# Generated by Django 3.2.5 on 2021-08-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_api', '0005_auto_20210804_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentImage',
        ),
    ]
