# Generated by Django 3.2.5 on 2021-08-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_api', '0006_auto_20210810_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='authour',
            new_name='author',
        ),
    ]
