# Generated by Django 3.2.5 on 2021-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_idx', models.IntegerField()),
                ('notification_type', models.CharField(choices=[('group', 'group'), ('comment', 'comment')], max_length=20)),
            ],
        ),
    ]
