# Generated by Django 3.2.6 on 2021-08-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('group', 'group'), ('comment', 'comment')], max_length=20),
        ),
    ]
