# Generated by Django 3.2.6 on 2021-09-13 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_api', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed_api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('object_feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed_api.feed')),
                ('object_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group_api.group')),
                ('object_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
