# Generated by Django 3.2.5 on 2021-07-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='department',
            field=models.IntegerField(),
        ),
    ]
