# Generated by Django 3.2.5 on 2021-07-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_usercustom_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='department',
            field=models.IntegerField(choices=[(0, '산업경영공학과'), (1, '기계공학과'), (2, '컴퓨터공학과'), (3, '그외')]),
        ),
    ]
